### ISSUE TITLE
Use AMI tags to discover AMI id 

### ISSUE THREAD

**Issue by mauricios** [Aplyca/ansible-role-ec2launch#1]
In order to be more explicit and better documented it is better to use the AMI tags to discover the AMI id

``` yaml
ec2launch:
  ami_tags:
    Name: "App AMI"
    Version: "1.0.0"
```

The instance is launched only if one AMI is found, otherwise it should fail with proper message.
